// Minimal ABIs — only the entries the frontend calls.

export const erc20Abi = [
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
  },
  { type: "function", name: "faucet", stateMutability: "nonpayable", inputs: [], outputs: [] },
] as const;

export const factoryAbi = [
  {
    type: "function",
    name: "createLoanVault",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "loanParams",
        type: "tuple",
        components: [
          { name: "borrowerRef", type: "bytes32" },
          { name: "principal", type: "uint256" },
          { name: "rateBps", type: "uint256" },
          { name: "termDays", type: "uint32" },
          { name: "repaymentType", type: "uint8" },
          { name: "installments", type: "uint32" },
          { name: "risk", type: "uint8" },
          { name: "agreementHash", type: "bytes32" },
          { name: "dossierURI", type: "string" },
          { name: "description", type: "string" },
          { name: "nextInstallmentAmount", type: "uint256" },
          { name: "nextDueDate", type: "uint256" },
        ],
      },
      {
        name: "p",
        type: "tuple",
        components: [
          { name: "asset", type: "address" },
          { name: "admin", type: "address" },
          { name: "allocator", type: "address" },
          { name: "name", type: "string" },
          { name: "symbol", type: "string" },
          { name: "maxDeposits", type: "uint256" },
          { name: "lzEndpoint", type: "address" },
          { name: "tranched", type: "bool" },
          { name: "whitelistEnabled", type: "bool" },
        ],
      },
    ],
    outputs: [
      { name: "vault", type: "address" },
      { name: "loanId", type: "uint256" },
    ],
  },
  { type: "function", name: "allVaults", stateMutability: "view", inputs: [], outputs: [{ type: "address[]" }] },
  { type: "function", name: "owner", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "loanRegistry", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  {
    type: "function",
    name: "whitelistedAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address[]" }],
  },
  {
    type: "function",
    name: "isAssetWhitelisted",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "whitelistAsset",
    stateMutability: "nonpayable",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "unwhitelistAsset",
    stateMutability: "nonpayable",
    inputs: [{ name: "asset", type: "address" }],
    outputs: [],
  },
] as const;

export const loanRegistryAbi = [
  {
    type: "function",
    name: "getLoan",
    stateMutability: "view",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "vault", type: "address" },
          { name: "borrowerRef", type: "bytes32" },
          { name: "principal", type: "uint256" },
          { name: "rateBps", type: "uint256" },
          { name: "termDays", type: "uint32" },
          { name: "repaymentType", type: "uint8" },
          { name: "installments", type: "uint32" },
          { name: "risk", type: "uint8" },
          { name: "agreementHash", type: "bytes32" },
          { name: "dossierURI", type: "string" },
          { name: "description", type: "string" },
          { name: "status", type: "uint8" },
          { name: "amountRepaid", type: "uint256" },
          { name: "installmentsPaid", type: "uint32" },
          { name: "nextInstallmentAmount", type: "uint256" },
          { name: "nextDueDate", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "recordRepayment",
    stateMutability: "nonpayable",
    inputs: [
      { name: "loanId", type: "uint256" },
      { name: "newNextDueDate", type: "uint256" },
    ],
    outputs: [{ type: "uint8" }],
  },
  {
    type: "function",
    name: "restructureLoan",
    stateMutability: "nonpayable",
    inputs: [
      { name: "loanId", type: "uint256" },
      {
        name: "p",
        type: "tuple",
        components: [
          { name: "principal", type: "uint256" },
          { name: "rateBps", type: "uint256" },
          { name: "termDays", type: "uint32" },
          { name: "installments", type: "uint32" },
          { name: "nextInstallmentAmount", type: "uint256" },
          { name: "nextDueDate", type: "uint256" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setStatus",
    stateMutability: "nonpayable",
    inputs: [
      { name: "loanId", type: "uint256" },
      { name: "status", type: "uint8" },
    ],
    outputs: [],
  },
] as const;

export const vaultAbi = [
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "asset", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "owner", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "allocator", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "totalAssets", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "totalSupply", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "totalDeposits", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "maxDeposits", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "loanRegistry", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "loanId", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "custodied", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "state", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "tranched", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "bufferAmount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "recoveryRecorded", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "whitelistEnabled", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  {
    type: "function",
    name: "isDepositorWhitelisted",
    stateMutability: "view",
    inputs: [{ name: "depositor", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "setDepositorWhitelist",
    stateMutability: "nonpayable",
    inputs: [
      { name: "depositors", type: "address[]" },
      { name: "allowed", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "depositBuffer",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  { type: "function", name: "withdrawBuffer", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "depositsOpen", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "withdrawalsOpen", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "convertToAssets",
    stateMutability: "view",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "maxDeposit",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "receiver", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "redeem",
    stateMutability: "nonpayable",
    inputs: [
      { name: "shares", type: "uint256" },
      { name: "receiver", type: "address" },
      { name: "owner", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "receiver", type: "address" },
      { name: "owner", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "startFunding", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "startCustody", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "closeVault", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "custodyFunds",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "recordRepayment",
    stateMutability: "nonpayable",
    inputs: [{ name: "newNextDueDate", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "recordRecovery",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
] as const;
